//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gross_marign
    {
        public int gross_marign_id { get; set; }
        public string description { get; set; }
        public System.DateTime gross_date { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
