//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class institute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public institute()
        {
            this.section_institute = new HashSet<section_institute>();
            this.projects = new HashSet<project>();
            this.users = new HashSet<user>();
            this.messages = new HashSet<message>();
        }
    
        public int institute_id { get; set; }
        public string institutename { get; set; }
        public string institute_fulladdress { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> adress_id { get; set; }
        public string someNEWCOL { get; set; }
    
        public virtual department department { get; set; }
        public virtual institute_address institute_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<section_institute> section_institute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        public virtual institute_type institute_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
    }
}
