//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class institute_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public institute_address()
        {
            this.institutes = new HashSet<institute>();
        }
    
        public int institute_adress_id { get; set; }
        public Nullable<int> governmnetcode { get; set; }
        public Nullable<int> citycode { get; set; }
        public Nullable<int> stationcode { get; set; }
    
        public virtual city city { get; set; }
        public virtual governmnet governmnet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<institute> institutes { get; set; }
        public virtual station station { get; set; }
    }
}
