//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_roles
    {
        public int id { get; set; }
        public int job_id { get; set; }
        public int role_id { get; set; }
    
        public virtual job job { get; set; }
        public virtual role role { get; set; }
    }
}
