//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagedetail
    {
        public int messageNum { get; set; }
        public int archiveNum { get; set; }
        public int messageType { get; set; }
        public System.DateTime messageDate { get; set; }
        public System.DateTime messageDateSentRecieved { get; set; }
        public Nullable<System.DateTime> lastDateReplay { get; set; }
        public sbyte messageFollow { get; set; }
        public string projectName { get; set; }
        public string replyText { get; set; }
        public System.DateTime replyDate { get; set; }
        public string attachment { get; set; }
        public string tagName { get; set; }
        public string userAccess { get; set; }
    }
}
