//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_reply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message_reply()
        {
            this.reply_attachments = new HashSet<reply_attachments>();
        }
    
        public int ID { get; set; }
        public int mesaage_id { get; set; }
        public System.DateTime reply_date { get; set; }
        public string reply_text { get; set; }
        public int user_id { get; set; }
    
        public virtual message message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reply_attachments> reply_attachments { get; set; }
        public virtual user user { get; set; }
    }
}
