//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class milestone
    {
        public int milestone_id { get; set; }
        public string milestone_name { get; set; }
        public System.DateTime deadline { get; set; }
        public int project_id { get; set; }
        public Nullable<sbyte> reached { get; set; }
    
        public virtual project project { get; set; }
    }
}
