//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section_institute
    {
        public int section_id { get; set; }
        public int insti_id { get; set; }
        public int id { get; set; }
    
        public virtual institute institute { get; set; }
        public virtual section section { get; set; }
    }
}
