//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_logs
    {
        public int task_id { get; set; }
        public int log_id { get; set; }
        public int ID { get; set; }
    
        public virtual log log { get; set; }
        public virtual task task { get; set; }
    }
}
